### ISSUE TITLE
Invalid xpath selector causing nuisance exceptions to be printed

### ISSUE THREAD

**Issue by codylandry** [mailgun/talon#114]
I'm using talon to remove quotations from emails and, each time the extract_from_html method is called, this is printed to console:

```
xmlXPathCompOpEval: function text_content bound to undefined prefix mg
2016-09-28 09:26:09,510 - talon.quotations - ERROR - ERROR extracting message
Traceback (most recent call last):
  File "/Users/codylandry/PycharmProjects/servicefusion/venv/lib/python2.7/site-packages/talon/quotations.py", line 177, in extract_from
    return extract_from_html(msg_body)
  File "/Users/codylandry/PycharmProjects/servicefusion/venv/lib/python2.7/site-packages/talon/quotations.py", line 362, in extract_from_html
    result = _extract_from_html(msg_body)
  File "/Users/codylandry/PycharmProjects/servicefusion/venv/lib/python2.7/site-packages/talon/quotations.py", line 398, in _extract_from_html
    html_quotations.cut_from_block(html_tree)
  File "/Users/codylandry/PycharmProjects/servicefusion/venv/lib/python2.7/site-packages/talon/html_quotations.py", line 162, in cut_from_block
    ("//*[starts-with(mg:text_content(), 'From:')]|"
  File "src/lxml/lxml.etree.pyx", line 1587, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:57923)
  File "src/lxml/xpath.pxi", line 307, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:167084)
  File "src/lxml/xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:166043)
XPathEvalError: Invalid expression
```

I have narrowed this down to html_quotations.cut_from_block.  The exception is thrown on the first line here:

```
block = html_message.xpath(
        ("//*[starts-with(mg:text_content(), 'From:')]|"
         "//*[starts-with(mg:text_content(), 'Date:')]"))
```

I am unfamiliar with xpath, but shouldn't there be a way to validate the selector prefix before proceeding?

I was able to disable the logging message from talon but this line seems to be coming from lxml?  

```
xmlXPathCompOpEval: function text_content bound to undefined prefix mg
```

Any help would be greatly appreciated,  these messages are taking over our consoles!

**Comment by obukhov-sergey** [comment]
You should call ``talon.init()`` first - it should register the missing extension:

```python
import talon

talon.init()
```
