### ISSUE TITLE
Doesn't work without ML deps; seems like a circular import issue

### ISSUE THREAD

**Issue by alexei** [mailgun/talon#131]
See also #130

I tried manually installing the deps (all except numpy, scipy, scikit-learn) in order to use the bruteforce method of extracting signatures, an attempt which results in the following:
```
>>> from talon.signature.bruteforce import extract_signature
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/alexei/.virtualenvs/project/lib/python2.7/site-packages/talon/signature/__init__.py", line 26, in <module>
    from . import extraction
  File "/Users/alexei/.virtualenvs/project/lib/python2.7/site-packages/talon/signature/extraction.py", line 7, in <module>
    import numpy
ImportError: No module named numpy
```

After installing the numpy package, I get the following:
```
>>> from talon.signature.bruteforce import extract_signature
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/alexei/.virtualenvs/project/lib/python2.7/site-packages/talon/signature/__init__.py", line 26, in <module>
    from . import extraction
ImportError: cannot import name extraction
```

Looks like a circular import issue.

**Comment by obukhov-sergey** [comment]
Should be fixed in latest master. Took extras approach.
