### ISSUE TITLE
error in importing signature

### ISSUE THREAD

**Issue by arjuniyer1978** [mailgun/talon#229]
import talon
from talon import quotations
from talon import signature
.\email_extract.py
Traceback (most recent call last):
  File ".\email_extract.py", line 6, in <module>
   
  File "c:\users\local\AppData\Local\Programs\Python\Python37\lib\site-packages\talon\signature\learning\classifier.py", line 34, in load
    return joblib.load(saved_classifier_filename)
  File "c:\users\local\AppData\Local\Programs\Python\Python37\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "c:\users\local\AppData\Local\Programs\Python\Python37\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "c:\users\local\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "c:\users\local\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "c:\users\local\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.svm.classes'

following are the versions - 
Talon - 1.4.4
scikit-learn -  0.24.1 ( read few threads that scikit-learn has to be a lower version)
joblib -  1.1.0

If i go to lower sckit versions, i get lot of deprecated np.float64 usage warnings.

Could someone please share the right versions for scikit-learn, talon , dependencies that would work with python 3.7 and higher?
Thanks

**Comment by Samwellwang** [comment]
https://github.com/mailgun/talon/issues/231#issuecomment-2369964190

**Comment by obukhov-sergey** [comment]
Please install from github master branch untill the PyPi is updated.
